version: '2'
services:
  config-server:
    build: config-server
    ports:
     - "8888:8888"

  discovery-server:
    build: discovery-server
    ports:
     - "8761:8761"
    depends_on:
     - config-server
 
  main-gateway:
    build: main-gateway
    ports:
     - "8080:8080"
    depends_on:
     - config-server
     - discovery-server

  scheduler-service:
    build: scheduler-service
    depends_on:
     - config-server
     - discovery-server

  storage-service:
    build: storage-service
    depends_on:
     - config-server
     - discovery-server