scraper:
  data:
    neo4j:
      user: neo4j
      password: password
      host: chan-neo4j-data
  web:
    user-agent: Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6
    referrer: http://www.google.com
    timeout: 10000