server:
  port: 8761

eureka:
  instance:
    hostname: discovery-serer
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://discovery-server:${server.port}/eureka/

spring:
  cloud:
    config:
      discovery:
        enabled: true